version: 2

models:
  - name: dim_listings_cleansed
    description: Cleansed table that contains Airbnb listings
    columns:
      - name: listing_id
        description: Primary key for the listing
        tests:
          - unique
          - not_null
      - name: host_id
        description: The host's id. References to the host table
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id
      - name: room_type
        description: Type of the apartment/room
        tests:
          - accepted_values:
              values: ['Entire home/apt', 'Private room', 'Shared room', 'Hotel room']
      - name: minimum_nights
        description: '{{doc("dim_listing_cleansed__minimum_nights")}}'
        tests:
          - positive_value

  - name: dim_hosts_cleansed
    description: Cleansed table that contains Airbnb hosts
    columns:
      - name: host_id
        description: The primary key of the hosts table.
        tests:
          - not_null
          - unique

      - name: host_name
        description: The name of the host
        tests:
          - not_null

      - name: is_superhost
        description: Indicates if the host is a superhost. 't' means superhost 'f' means non-superhost.
        tests:
          - accepted_values:
              values: ['t', 'f']

      - name: created_at
        description: The time stamp for the creation of the host user

      - name: updated_at
        description: The time stamp for the update of the host user        

  - name: dim_listings_w_hosts
    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          compare_model: source('airbnb', 'listings')
    columns:
      - name: price
        tests:
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: .99
              min_value: 50 # (Optional)
              max_value: 500 # (Optional)
          - dbt_expectations.expect_column_max_to_be_between:
              max_value: 5000
              severity: warn
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number

